Solution
mate-academy/js_herbivores_and_carnivores pull request #1253
Opened 2022-11-26 16:53 UTC by Oleksandr-Filo

2022-12-10 10:58 UTC, Nazar-Brunarskyi approved these changes
🔥

2022-12-13 09:24 UTC, valerii-derkach requested changes

2022-12-13 09:24 UTC, valerii-derkach commented on src/herbivoresAndCarnivores.js
> +    }
```suggestion
  bite(beast) {
    if (beast instanceof Herbivore && !beast.hidden) {
      beast.health -= 50;
    }
```

2022-12-13 11:16 UTC, Oleksandr-Filo commented on src/herbivoresAndCarnivores.js
> +    }
fixed

2022-12-13 15:01 UTC, valerii-derkach approved these changes

2026-03-30 13:38 UTC, closed without merging