NVyrsta
mate-academy/js_herbivores_and_carnivores pull request #1386
Opened 2023-01-05 18:07 UTC by NVyrsta

2023-01-07 20:10 UTC, Avichez approved these changes
Great solution 👍 
I forgot about such a simple method filter 🥲

2023-01-10 08:45 UTC, alexandra-protyanova requested changes

2023-01-10 08:45 UTC, alexandra-protyanova commented on src/herbivoresAndCarnivores.js
> +    this.health = health || 100;
`health` is not passed as an argument by the task

2023-01-10 08:45 UTC, alexandra-protyanova commented on src/herbivoresAndCarnivores.js
> +  }
```suggestion
  constructor(name) {
    super(name);
    this.hidden = false;
  }

  hide() {
    this.hidden = !this.hidden;
  }
```

2023-01-11 09:02 UTC, alexandra-protyanova approved these changes

2023-06-07 09:38 UTC, closed without merging