solution
mate-academy/js_herbivores_and_carnivores pull request #1813
Opened 2023-05-29 21:44 UTC by vitvadym

2023-05-31 07:03 UTC, 33Orange requested changes
Good job.

A few moments to fix

2023-05-31 07:03 UTC, 33Orange commented on src/herbivoresAndCarnivores.js
> +  }
I do not see in the conditions of the task that the damage of a predator can be different. Let's do everything according to the conditions
```suggestion

```

2023-05-31 07:03 UTC, 33Orange commented on src/herbivoresAndCarnivores.js
> +      : animal.health = this.health;
Why you use ternary operator here?
We use ternary operator only if we do smth in every case, but here you do smth only if condition `true`.

```suggestion
    if (animal instanceof Herbivore && !animal.hidden) {
      animal.health -= this.damage
    }
```

2023-06-12 04:56 UTC, silchyn approved these changes

2023-06-12 04:56 UTC, silchyn commented on src/herbivoresAndCarnivores.js
> +  static removeDiedAmimals() {
```suggestion
  static removeDeadAmimals() {
```

2024-11-22 21:05 UTC, closed without merging