Solution
mate-academy/js_herbivores_and_carnivores pull request #2967
Opened 2024-07-21 18:21 UTC by MaxBorovique

2024-07-21 18:22 UTC, mateacademy-ai-mentor requested changes
Thank you for your hard work! 👍 It looks like we need to make sure the `bite` method adheres to the task specifications by adding a check against `Carnivore` instances. Also, let's remove the `takeDamage` method from the `Herbivore` class to align with the task requirements. These changes will help ensure your code meets the functionality expected. Keep up the great effort! 😊

2024-07-21 18:22 UTC, mateacademy-ai-mentor commented on src/herbivoresAndCarnivores.js
> +  }
The `takeDamage` method should not be a part of the `Herbivore` class as it is not specified in the task requirements. The task description implies that health management should be handled by the `bite` method of the `Carnivore` class. Consider removing this method and implementing health decrement directly in the `bite` method while ensuring the removal of the animal from the `Animal.alive` array if its health drops to 0 or below.

2024-07-21 18:22 UTC, mateacademy-ai-mentor commented on src/herbivoresAndCarnivores.js
> +  bite(herbivore) {
The `bite` method should check if the target is not an instance of `Carnivore`. Currently, it only checks if the target is an instance of `Herbivore`, but the task specifies that the method should not work if the target is another carnivore. Add a condition to ensure that the `bite` method does not affect `Carnivore` instances.

2024-07-22 07:40 UTC, Moroz-Dmytro requested changes

2024-07-22 07:40 UTC, Moroz-Dmytro commented on src/herbivoresAndCarnivores.js
> +  constructor(name, health = 100) {
Magic value `100`, create variable

2024-07-22 07:40 UTC, Moroz-Dmytro commented on src/herbivoresAndCarnivores.js
> +        target.health -= 50;
Magic value `50`, create variable

2024-07-22 07:40 UTC, Moroz-Dmytro commented on src/herbivoresAndCarnivores.js
> +      if (!target.hidden) {
```suggestion
    if (!(target instanceof Carnivore) && !target.hidden) {
```

2024-07-22 07:40 UTC, Moroz-Dmytro commented on src/herbivoresAndCarnivores.js
> +  }
Delete this function, you don't use it

2024-07-22 11:21 UTC, MaxBorovique commented on src/herbivoresAndCarnivores.js
> +        target.health -= 50;
Thank you for whis comment. 
Done

2024-07-22 12:16 UTC, ArturErmolenko approved these changes

2024-07-22 12:16 UTC, ArturErmolenko commented on src/herbivoresAndCarnivores.js
> +  constructor(name, health = MAX_HEALTH, hidden = false) {
```suggestion
  constructor(
    name, health = MAX_HEALTH,
    hidden = false,
    ) {
```

2025-03-03 19:47 UTC, closed without merging