IsDrozdovHere?
mate-academy/js_herbivores_and_carnivores pull request #426
Opened 2021-09-28 16:37 UTC by Vladyslav-Banul

2021-09-29 10:56 UTC, BesConstantine approved these changes
Хорошая работа.

P.S.: понравились название PR, переменных и методов :)

2021-09-29 10:56 UTC, BesConstantine commented on src/herbivoresAndCarnivores.js
> +    }
ты каждый раз при создании животного проверяешь нужно ли создавать массив. Может лучше создать его вне конструктора?

2021-09-29 10:56 UTC, BesConstantine commented on src/herbivoresAndCarnivores.js
> +    }
Возможно хотели что бы мы делали проверку по наличия класса, если же нет - то хорошая идея добавить тип животного и проверять по нему.

2021-09-29 18:54 UTC, Ihor-Karpyn requested changes

2021-09-29 18:54 UTC, Ihor-Karpyn commented on src/herbivoresAndCarnivores.js
> +    }
погоджуюсь з костюю, створи цей масив зразу і при створені завжди добавляй нову тварину

2021-09-29 18:54 UTC, Ihor-Karpyn commented on src/herbivoresAndCarnivores.js
> +  }
краще створи функцію updateAnimalsList яка просто буде фільтрували ліст від мертвих тварин

2021-09-29 18:54 UTC, Ihor-Karpyn commented on src/herbivoresAndCarnivores.js
> +    }
```suggestion
  bite(target) {
    if (!target.hidden && target.type === 'herbivore') {
      target.health -= 50;
    }
```

2021-09-29 18:54 UTC, Ihor-Karpyn commented on src/herbivoresAndCarnivores.js
> +      victim.removeCorpse(victim.name);
```suggestion
      Animals.updateAnimalsList();
```

2021-10-04 09:42 UTC, OleksiiBlezniuk approved these changes
Good job! 🚀

2022-10-28 10:01 UTC, closed without merging