solution
mate-academy/js_herbivores_and_carnivores pull request #693
Opened 2022-04-06 11:09 UTC by sever2kk

2022-04-06 12:18 UTC, Bohdan-Maksymiuk requested changes
Good job, but don’t forget to check checklist )

2022-04-06 12:18 UTC, Bohdan-Maksymiuk commented on src/herbivoresAndCarnivores.js
> +    this.hidden ? this.hidden = false : this.hidden = true;
```suggestion
    this.hidden = !this.hidden;
```

2022-04-06 12:18 UTC, Bohdan-Maksymiuk commented on src/herbivoresAndCarnivores.js
> +    this.hidden ? this.hidden = false : this.hidden = true;
https://github.com/mate-academy/js_herbivores_and_carnivores/blob/master/checklist.md

2022-04-06 13:08 UTC, sever2kk commented on src/herbivoresAndCarnivores.js
> +    this.hidden ? this.hidden = false : this.hidden = true;
My fault, sorry(

2022-04-06 13:09 UTC, sever2kk commented on src/herbivoresAndCarnivores.js
> +    this.hidden ? this.hidden = false : this.hidden = true;
My fault, sorry :)

2022-04-07 08:28 UTC, Bohdan-Maksymiuk approved these changes
Great 🪄

2026-07-17 03:06 UTC, closed without merging