solution
mate-academy/js_herbivores_and_carnivores pull request #791
Opened 2022-05-19 16:09 UTC by PRO-GRAM-MER

2022-05-22 15:23 UTC, amitpatiljc commented on src/herbivoresAndCarnivores.js
> +    if (!(victim instanceof Carnivore) && !victim.hidden) {
I think you can just use instanceof Herbivore to make your code more simple

2022-05-22 15:24 UTC, amitpatiljc requested changes
Good Job! Just one suggestion.

2022-05-25 03:38 UTC, amitpatiljc approved these changes
Good job 👍

2022-05-25 07:14 UTC, meforoma approved these changes

2026-03-29 20:35 UTC, closed without merging