solution
mate-academy/js_herbivores_and_carnivores pull request #965
Opened 2022-08-18 11:45 UTC by tiserett

2022-08-19 09:14 UTC, aleksandra-prognimak approved these changes
🔥🔥🔥

2022-08-22 08:32 UTC, danylo-onishchuk requested changes

2022-08-22 08:32 UTC, danylo-onishchuk commented on src/herbivoresAndCarnivores.js
> +    this.hidden = true;
changes the hidden property of the beast to the opposite value

2022-08-22 08:43 UTC, tiserett commented on src/herbivoresAndCarnivores.js
> +    this.hidden = true;
![image](https://user-images.githubusercontent.com/101139968/185878918-ae920998-cf5e-4670-b430-e89cc37a0a4c.png)

2022-08-22 08:48 UTC, danylo-onishchuk requested changes

2022-08-22 08:48 UTC, danylo-onishchuk commented on src/herbivoresAndCarnivores.js
> +    this.hidden = true;
Задание явно важнее чек листа. 

Create a Herbivore class. Herbivore has a method of hide, which changes the hidden property of the beast to the opposite value and helps to hide from carnivores.

нужно, чтоб была возможность изменять это свойство на обратное. 

спасибо, что обратил внимание на чек лист, скорее всего это ошбика

2022-08-22 08:54 UTC, tiserett commented on src/herbivoresAndCarnivores.js
> +    this.hidden = true;
изначально оно менялось на обратное, но после чеклиста пришлось переделать, щас исправлю

2022-08-22 14:33 UTC, danylo-onishchuk approved these changes

2024-03-09 11:18 UTC, closed without merging